only support single mode
okx/exchain pull request #2329
Opened 2022-07-21 09:24 UTC by Ywmet

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

2022-07-23 08:22 UTC, KamiD requested changes

2022-07-23 08:22 UTC, KamiD commented on libs/cosmos-sdk/x/auth/ante/sigverify.go
> +			return ctx, sdkerrors.Wrap(sdkerrors.ErrInvalidSignBytes, "signBytes is nil")
this is a new case that returns an error if signByte == nil, it has some risks to smb

2022-07-26 09:58 UTC, BananaLF commented on libs/cosmos-sdk/x/auth/types/stdtx_adapter.go
> +		return nil
this line panic is much better

2022-07-26 11:15 UTC, KamiD approved these changes

2022-07-26 11:25 UTC, merged