fix the error of invalid min gas price in evm tx
okx/exchain pull request #608
Opened 2021-01-28 12:49 UTC by AaronZgl

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

2021-01-28 22:15 UTC, zhongqiuwood reviewed
ut requried

2021-01-30 02:43 UTC, AaronZgl commented
> ut requried

Done!

2021-01-30 07:04 UTC, zhongqiuwood approved these changes, later dismissed

2021-01-30 07:04 UTC, zhongqiuwood commented on app/ante/eth.go
> +	minGasPrices := ctx.MinGasPrices().MulDec(sdk.NewDecFromBigInt(math.BigPow(10, sdk.Precision)))
magic number is not allowed

2021-01-31 03:37 UTC, AaronZgl commented on app/ante/eth.go
> +	minGasPrices := ctx.MinGasPrices().MulDec(sdk.NewDecFromBigInt(math.BigPow(10, sdk.Precision)))
fixed it!

2021-01-31 04:08 UTC, KamiD requested changes

2021-01-31 04:08 UTC, KamiD commented on app/ante/eth.go
> +	coinUnit := sdk.NewDecFromBigInt(math.BigPow(10, sdk.Precision))
magic number is not allowed, what's the exactly means of 10

2021-01-31 09:51 UTC, closed without merging