add gas refund handler
okx/exchain pull request #770
Opened 2021-03-24 10:53 UTC by AaronZgl

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

2021-03-26 11:07 UTC, KamiD requested changes
gas refund only works on evm tx

2021-03-26 11:18 UTC, summerpro approved these changes, later dismissed

2021-03-26 12:23 UTC, AaronZgl commented
> gas refund only works on evm tx

The cosmos gas refund function has been removed.

2021-03-28 01:47 UTC, xiangjianmeng submitted a review, later dismissed

2021-03-28 01:47 UTC, xiangjianmeng commented on app/refund/refund.go
> +type GasRefundHandler struct {
may consider `GasRefund`

2021-03-28 01:47 UTC, xiangjianmeng commented on app/refund/refund.go
> +
may consider `Refund`

2021-03-29 02:20 UTC, xiangjianmeng approved these changes, later dismissed

2021-03-29 08:06 UTC, summerpro submitted a review, later dismissed

2021-03-29 08:43 UTC, xiangjianmeng approved these changes, later dismissed

2021-03-29 08:50 UTC, KamiD approved these changes, later dismissed

2021-03-29 09:35 UTC, KamiD approved these changes

2021-03-29 09:36 UTC, xiangjianmeng approved these changes

2021-03-29 09:36 UTC, summerpro approved these changes

2021-03-29 09:38 UTC, merged