0x prefixed address format supported
okx/exchain pull request #973
Opened 2021-08-16 20:31 UTC by kl456123

- Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/okex/okexchain/blob/develop/CONTRIBUTING.md#pr-targeting))

- [ ] Linked to github-issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote tests
- [ ] Updated relevant documentation (`docs/`)
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Reviewed `Files changed` in the github PR explorer

______

For Admin Use:
- Added appropriate labels to PR (ex. wip, ready-for-review, docs)
- Reviewers Assigned
- Squashed all commits, uses message "Merge PR #XYZ: [title]" ([coding standards](https://github.com/okex/coding/blob/master/README.md#merging-a-pr))

2021-08-16 21:50 UTC, sheyla2514 approved these changes, later dismissed

2021-08-17 02:10 UTC, KamiD requested changes

2021-08-17 02:10 UTC, KamiD commented on x/evm/client/cli/query.go
> +    }
can not append 0x prefix directly

2021-08-17 03:59 UTC, kl456123 commented on x/evm/client/cli/query.go
> +    }
call "accountToHex" api to fix it

2021-08-20 03:13 UTC, KamiD approved these changes

2021-08-20 03:32 UTC, merged